name: Prevent scheduled workflow from being automatically disabled

on:
  schedule:
    # UTC の 06:00 は JST だと 15:00 。
    - cron: '0 5 1 * *'
  workflow_dispatch:

concurrency:
  group: keepalive
  cancel-in-progress: false

jobs:

  keepalive:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:

      - name: Re-enable workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh workflow enable keepalive.yml
          gh workflow enable github-actions-demo.yml
